#!/bin/bash

# Auto-Build Environment Setup for Bodii iOS Project
# Generated by Planner Agent

set -e

echo "========================================"
echo "Bodii iOS Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# ============================================
# PREREQUISITES CHECK
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Xcode
if ! command -v xcodebuild &> /dev/null; then
    echo -e "${RED}Error: Xcode not found${NC}"
    echo "Please install Xcode from the App Store"
    exit 1
fi

XCODE_VERSION=$(xcodebuild -version | head -1)
echo -e "${GREEN}✓ $XCODE_VERSION${NC}"

# Check macOS version
MACOS_VERSION=$(sw_vers -productVersion)
echo -e "${GREEN}✓ macOS $MACOS_VERSION${NC}"

# Check for iOS Simulator
if ! xcrun simctl list devices | grep -q "iPhone 15"; then
    echo -e "${YELLOW}Warning: iPhone 15 Simulator not found${NC}"
    echo "You may need to download iOS 17+ Simulator via Xcode"
fi

# ============================================
# PROJECT STATUS
# ============================================

echo ""
echo "----------------------------------------"
echo "Project Status"
echo "----------------------------------------"

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$PROJECT_DIR"

if [ -d "Bodii.xcodeproj" ]; then
    echo -e "${GREEN}✓ Xcode project exists${NC}"
else
    echo -e "${YELLOW}○ Xcode project not created yet${NC}"
    echo "  Create via: Xcode > File > New > Project > iOS App"
    echo "  Product Name: Bodii"
    echo "  Interface: SwiftUI"
    echo "  Storage: Core Data"
fi

if [ -d "Bodii/App" ]; then
    echo -e "${GREEN}✓ App folder structure exists${NC}"
else
    echo -e "${YELLOW}○ Folder structure not created${NC}"
fi

if [ -d "Bodii/Infrastructure/Persistence/Bodii.xcdatamodeld" ]; then
    echo -e "${GREEN}✓ Core Data model exists${NC}"
else
    echo -e "${YELLOW}○ Core Data model not created${NC}"
fi

# ============================================
# OPEN PROJECT
# ============================================

echo ""
echo "----------------------------------------"
echo "Opening Project"
echo "----------------------------------------"

if [ -d "Bodii.xcodeproj" ]; then
    echo "Opening Bodii.xcodeproj in Xcode..."
    open Bodii.xcodeproj
    echo -e "${GREEN}✓ Xcode opened${NC}"
else
    echo -e "${YELLOW}Cannot open project - not created yet${NC}"
fi

# ============================================
# BUILD INSTRUCTIONS
# ============================================

echo ""
echo "========================================"
echo "Build Instructions"
echo "========================================"
echo ""
echo "To build the project:"
echo "  xcodebuild -project Bodii.xcodeproj -scheme Bodii -destination 'platform=iOS Simulator,name=iPhone 15' build"
echo ""
echo "To run on simulator:"
echo "  1. Open Bodii.xcodeproj in Xcode"
echo "  2. Select iPhone 15 simulator"
echo "  3. Press Cmd + R"
echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
