#!/bin/bash

# Auto-Build Environment Setup for Bodii iOS App
# Generated by Planner Agent
# Spec: 004-project-foundation-core-data-model

set -e

echo "========================================"
echo "Bodii iOS Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# PRE-REQUISITES CHECK
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Xcode
if ! command -v xcodebuild &> /dev/null; then
    echo -e "${RED}Xcode command line tools not found${NC}"
    echo "Please install Xcode from the App Store"
    exit 1
fi
echo -e "${GREEN}Xcode found${NC}"

# Check Xcode version
XCODE_VERSION=$(xcodebuild -version | head -n1)
echo "  $XCODE_VERSION"

# Check for iOS Simulator
if ! xcrun simctl list devices | grep -q "iPhone 15"; then
    echo -e "${YELLOW}Warning: iPhone 15 Simulator not found${NC}"
    echo "  Run: open -a Simulator and download iOS runtime"
fi

# ============================================
# PROJECT VALIDATION
# ============================================

echo ""
echo "Validating project structure..."

PROJECT_ROOT="/Users/chacha/lab/Bodii"

# Check project file exists
if [ ! -d "$PROJECT_ROOT/Bodii.xcodeproj" ]; then
    echo -e "${RED}Bodii.xcodeproj not found${NC}"
    exit 1
fi
echo -e "${GREEN}Project file found${NC}"

# Check key directories exist
REQUIRED_DIRS=(
    "Bodii/App"
    "Bodii/Domain/Entities"
    "Bodii/Shared/Enums"
    "Bodii/Shared/Utils"
    "Bodii/Shared/Extensions"
    "Bodii/Infrastructure/Persistence"
)

for dir in "${REQUIRED_DIRS[@]}"; do
    if [ ! -d "$PROJECT_ROOT/$dir" ]; then
        echo -e "${YELLOW}Creating missing directory: $dir${NC}"
        mkdir -p "$PROJECT_ROOT/$dir"
    fi
done
echo -e "${GREEN}Directory structure validated${NC}"

# ============================================
# BUILD VERIFICATION
# ============================================

echo ""
echo "Running initial build verification..."

cd "$PROJECT_ROOT"

# Clean build folder first
echo "  Cleaning build folder..."
xcodebuild clean -project Bodii.xcodeproj -scheme Bodii -quiet 2>/dev/null || true

# Build the project
echo "  Building project..."
if xcodebuild -project Bodii.xcodeproj \
    -scheme Bodii \
    -destination 'platform=iOS Simulator,name=iPhone 15' \
    build 2>&1 | tail -3 | grep -q "BUILD SUCCEEDED"; then
    echo -e "${GREEN}Build succeeded${NC}"
else
    echo -e "${YELLOW}Warning: Build may have issues${NC}"
    echo "  Run 'xcodebuild build' to see full output"
fi

# ============================================
# DOCUMENTATION REFERENCES
# ============================================

echo ""
echo "Reference Documentation:"
echo "  - docs/04_ERD.md        - Entity structure and relationships"
echo "  - docs/02_FEATURE_SPEC.md - Business rules and validation"
echo "  - docs/06_ALGORITHM.md  - BMR/TDEE calculation formulas"
echo "  - docs/08_EDGE_CASES.md - Edge cases and error handling"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: Bodii iOS App"
echo "Tech Stack: Swift, SwiftUI, Core Data"
echo ""
echo "To open in Xcode:"
echo "  open Bodii.xcodeproj"
echo ""
echo "To build from command line:"
echo "  xcodebuild -project Bodii.xcodeproj -scheme Bodii \\"
echo "    -destination 'platform=iOS Simulator,name=iPhone 15' build"
echo ""
echo "To run tests:"
echo "  xcodebuild test -project Bodii.xcodeproj -scheme Bodii \\"
echo "    -destination 'platform=iOS Simulator,name=iPhone 15'"
echo ""
echo "========================================"
